# application.conf
app {
  name = "NYC-Yellow-Taxi-Analysis"
  environment = "local"
  
  paths {
    # Default paths, can be overridden by environment variables
    input_data = ${?INPUT_PATH}
    input_data = "../data/raw"
    
    output_data = ${?OUTPUT_PATH}
    output_data = "../data/processed"
    
    taxi_zones = ${?TAXI_ZONE_PATH}
    taxi_zones = "../data/taxi_zones.csv"
  }
  
  spark {
    master = "local[*]"
    # Configurations specifically required for Delta Lake
    sql.extensions = "io.delta.sql.DeltaSparkSessionExtension"
    sql.catalog.spark_catalog = "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  }
}
